\
[build]
target = "aarch64-unknown-none"

[target.aarch64-unknown-none]
rustflags = [
  "-C", "link-arg=-Tboot/linker.ld",
  "-C", "relocation-model=static",
  "-C", "panic=abort",
]
# use LLD (default for many bare-metal targets)
linker-flavor = "ld.lld"
